name: autokeras-text-classifier
channels:
  - defaults
dependencies:
  - cython=0.29
  - ipython=7.2.0
  - pandas=0.23.4
  - python=3.6.7
  - tensorflow-gpu=1.12.0
  - pip:
    - autokeras==0.3.1
    - sentencepiece==0.1.6

