name: autokeras-text-classifier
channels:
  - defaults
dependencies:
  - cython=0.28.5
  - ipython=6.5.0
  - python=3.5.2
  - tensorflow-gpu=1.10.0
  - pip:
    - autokeras==0.3.5
    - sentencepiece==0.1.6

